name: Build
on: [push, pull_request]
jobs:
  validation:
    name: "Validation"
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b
      - uses: gradle/wrapper-validation-action@56b90f209b02bf6d1deae490e9ef18b21a389cd4
  gradle:
    name: "Build"
    strategy:
      matrix:
        os: [ubuntu-22.04, macos-12, windows-2022]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b
    - uses: actions/setup-java@b6e674f4b717d7b0ae3baee0fbe79f498905dfde
      with:
        java-version: 11
    - uses: eskatos/gradle-command-action@87a9a15658c426a54dd469d4fc7dc1a73ca9d4a6
      with:
        arguments: build --parallel --continue