name: Build
on: [push, pull_request]
jobs:
  validation:
    name: "Validation"
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b
      - uses: gradle/wrapper-validation-action@5188e9b5527a0a094cee21e2fe9a8ca44b4629af
  gradle:
    name: "Build"
    strategy:
      matrix:
        os: [ubuntu-22.04, macos-12, windows-2022]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b
    - uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9
      with:
        java-version: 11
        distribution: zulu
    - uses: eskatos/gradle-command-action@4c39dd82cd5e1ec7c6fa0173bb41b4b6bb3b86ff
      with:
        arguments: build --parallel --continue
