name: Build
on: [push, pull_request]
jobs:
  validation:
    name: "Validation"
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744
      - uses: gradle/wrapper-validation-action@56b90f209b02bf6d1deae490e9ef18b21a389cd4
  gradle:
    name: "Build"
    strategy:
      matrix:
        os: [ubuntu-22.04, macos-12, windows-2022]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744
    - uses: actions/setup-java@b6e674f4b717d7b0ae3baee0fbe79f498905dfde
      with:
        java-version: 11
    - uses: eskatos/gradle-command-action@b3afdc78a7849557ab26e243ccf07548086da025
      with:
        arguments: build --parallel --continue